name: microsample
version: git
summary: An educational snap for a snapped flask microservice.
description: |
  Endpoint json: http://hostip:8080/api/info
  Endpoint to get service status: http://hostip:8080/  (Will return "Online" if OK)

grade: devel # must be 'stable' to release into candidate/stable channels

confinement: strict # use 'strict' once you have the right plugs and slots

# This helps, for example, build.snapcraft.io to build only on archs we can run on.
architectures:
  - build-on: amd64

base: core22

apps:
  microsample:
    command: bin/flask run -h 0.0.0.0
    daemon: simple
    restart-condition: always
    plugs: [network-bind]
    environment:
      FLASK_APP: ./server.py
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

parts:
  flask-server:
    # See 'snapcraft plugins'
    plugin: python 
    source: .
    python-packages: [ flask ]
    prime: 
      - server.py