name: microsample
version: git
summary: A simple flask microservice on 0.0.0.0:8080
description: |
  Get service status with: curl http://hostip:8080/  (Will return "Online" if OK)

grade: devel # must be 'stable' to release into candidate/stable channels

confinement: strict # use 'strict' once you have the right plugs and slots

# This helps, for example, build.snapcraft.io to build only on archs we can run on.
architectures:
  - build-on: amd64

base: core22

apps:
  microsample:
    command: bin/flask-wrapper
    daemon: simple
    restart-condition: always
    plugs: [network-bind]
    environment:
      FLASK_APP: ./server.py
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

parts:

  # Install all packages from requirements
  python-packages:
    plugin: python
    source: .
    python-requirements: ['requirements.txt']

    
# Use the dump plugin to place our sources (server.py etc.)
# and copy the server.py and the wrapper script in place.
  flask-server:
    plugin: dump
    source: .
    organize:
      server.py: bin/
      flask-wrapper: bin/
